"""add kanban fields to tareas

Revision ID: a05b3f66b624
Revises: 6dbce8c1e094
Create Date: 2026-07-04 14:15:52.982349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05b3f66b624'
down_revision: Union[str, None] = '6dbce8c1e094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridad', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comentarios', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_column('fecha_cierre')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('comentarios')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('prioridad')

    # ### end Alembic commands ###
