"""add stripe fields to tenant

Revision ID: a08cbc2267fe
Revises: a05b3f66b624
Create Date: 2026-07-04 14:20:41.172645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08cbc2267fe'
down_revision: Union[str, None] = 'a05b3f66b624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plan_actual', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estado_suscripcion', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('estado_suscripcion')
        batch_op.drop_column('plan_actual')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
