"""baseline_and_tenant

Revision ID: ef887679465e
Revises: 
Create Date: 2026-07-01 20:01:28.758808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef887679465e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre_empresa', sa.String(), nullable=False),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)

    op.create_table('agendamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('tipo_servicio', sa.Enum('especializado', 'domicilio_taller', name='tiposervicio'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('tipo_vivienda', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('patente', sa.String(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_termino', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('equipo', sa.String(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=True),
    sa.Column('utm_link', sa.String(), nullable=True),
    sa.Column('utm_source_real', sa.String(), nullable=True),
    sa.Column('nota_interna', sa.String(), nullable=True),
    sa.Column('boton_enviado', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('nota_compartida', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('razon_estado', sa.String(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamientos_id'), ['id'], unique=False)

    op.create_table('campos_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('tipo_campo', sa.String(), nullable=True),
    sa.Column('opciones', sa.String(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('tipo_servicio', sa.String(), nullable=True),
    sa.Column('subtipo_servicio', sa.String(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=True),
    sa.Column('nombre_tecnico', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campos_formulario_id'), ['id'], unique=False)

    op.create_table('dias_bloqueados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    with op.batch_alter_table('dias_bloqueados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dias_bloqueados_id'), ['id'], unique=False)

    op.create_table('respuestas_campos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('agendamiento_id', sa.Integer(), nullable=True),
    sa.Column('campo_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agendamiento_id'], ['agendamientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campo_id'], ['campos_formulario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respuestas_campos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respuestas_campos_id'), ['id'], unique=False)

    op.create_table('utm_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('agendamiento_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agendamiento_id'], ['agendamientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utm_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utm_registros_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utm_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utm_registros_id'))

    op.drop_table('utm_registros')
    with op.batch_alter_table('respuestas_campos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respuestas_campos_id'))

    op.drop_table('respuestas_campos')
    with op.batch_alter_table('dias_bloqueados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dias_bloqueados_id'))

    op.drop_table('dias_bloqueados')
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campos_formulario_id'))

    op.drop_table('campos_formulario')
    with op.batch_alter_table('agendamientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamientos_id'))

    op.drop_table('agendamientos')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
